#Processing library metadata
authors=[Bernhard Reitinger](https\://github.com/breiting)
categories=Hardware
maxRevision=0
minRevision=0
name=INDbox
paragraph=Reads a continuous serial signal (buttons, pot, distance) and exposes raw + normalized values for Processing sketches.
prettyVersion=0.2.0
sentence=Simple serial interface for the INDbox sensor device.
url=https\://github.com/breiting/indbox-processing
version=1
