name=INDbox
version=1
prettyVersion = 0.2.0
authors=[Bernhard Reitinger](https://github.com/breiting)
url=https://github.com/breiting/indbox-processing
categories=Hardware
sentence=Simple serial interface for the INDbox sensor device.
paragraph=Reads a continuous serial signal (buttons, pot, distance) and exposes raw + normalized values for Processing sketches.
minRevision=0
maxRevision=0
